https://www.ncbi.nlm.nih.gov/pmc/articles/PMC346238/pdf/pnas00447-0135.pdf

In [ ]:
import numpy as np

Initializing state and weights. Each neuron $i$ has two states: $V_i=0$ ("not firing") and $V_i=1$ ("firing at maximum rate").



In [ ]:
nodes = 5
V = np.random.choice([0,1], [nodes])
V

array([1, 1, 0, 0, 1])

The strength of connection is defined as $T_{ij}$.

In [ ]:
# w = np.random.choice([0, 1], size=(nodes, nodes))
T = np.random.randn(nodes, nodes)
T = np.triu(T) + np.triu(T, 1).T
T -= np.diag(np.diag(T))
T

array([[ 0.        ,  0.52136415, -1.72850411,  0.2672358 , -0.09124213],
       [ 0.52136415,  0.        ,  0.26461448, -0.72565861, -0.16262786],
       [-1.72850411,  0.26461448,  0.        ,  0.14368891,  0.51561318],
       [ 0.2672358 , -0.72565861,  0.14368891,  0.        , -0.66581842],
       [-0.09124213, -0.16262786,  0.51561318, -0.66581842,  0.        ]])

The instantaneous state o the system is specified by listing the $N$ values of $V_i$, so it represented by a binary word of $N$ bits.

The state changes in time according to the following algorithm. For each neuron $i$ there is a fixed threshold $U_i$. (Unless otherwise stated, we choose $U_i = 0$).

In [ ]:
U = np.zeros([nodes])
U

array([0., 0., 0., 0., 0.])

Each neuron readjusts its state randomly in time but with a mean attempt rate W, setting

$$
V_i → 1 \, \text{if} \, \sum_{j \neq i} T_{ij}V_j \geq U_i
$$

and

$$
V_i → 0 \, \text{if} \, \sum_{j \neq i} T_{ij}V_j < U_i
$$

Thus, each neuron randomly and asynchronously evaluates whether it is above or below threshold and readjusts accordingly.

Suppose we wish to store the set of states $V^s$, $s = 1 \cdots n$. We use the storage prescription

$$
T_{ij} = \sum_s (2*V_i^s -1)(2*V_j^s -1)
$$

but with $T_{ii}=0$.

Alright, let's try this out with a simple example state to store: $V^s = [[1,0,1,1,0]]$. Then

In [ ]:
V_example = np.array([1,0,1,1,0])
T_example = np.zeros([nodes, nodes])

for i in range(nodes):
  for j in range(nodes):
    T_example[i,j] = (2*V_example[i] - 1) * (2*V_example[j] - 1)

T_example -= np.diag(np.diag(T_example))
T_example

array([[ 0., -1.,  1.,  1., -1.],
       [-1.,  0., -1., -1.,  1.],
       [ 1., -1.,  0.,  1., -1.],
       [ 1., -1.,  1.,  0., -1.],
       [-1.,  1., -1., -1.,  0.]])

So now `T_example` is the connection strength between each of the neurons.